require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - vendor/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - Guardfile
    - public/**/*

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/initializers/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'

Layout/LineLength:
  Exclude:
    - 'app/components/ui.rb'
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15

Rails/SkipsModelValidations:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
