version: '3.9'

services:
  redis:
    image: redis:6.2.6
    ports:
      - '6380:6379'
    volumes:
      - redis:/var/lib/redis/data
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
  web:
    image: devchallenge-platform_web:latest
    volumes:
      - web:/devchallenge
    ports:
      - '8081:8080'
    depends_on:
      - redis
      - sidekiq

volumes:
  db:
  redis:
  web:
