default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL") { 5 } %>

development:
  <<: *default
  database: devchallenge_development

test:
  <<: *default
  database: devchallenge_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
